/**
 * NOTIFICATION & RENEWAL TYPES
 *
 * These types define the shape of data for the renewals dashboard
 * and notification system.
 *
 * UPCOMING RENEWAL:
 * A contract that's approaching its end date. Includes an "urgency"
 * field that the frontend uses to show color-coded rows:
 * - Red for critical/expired
 * - Orange for warning (60 days)
 * - Blue for attention (90 days)
 * - Green for normal (90+ days)
 *
 * NOTIFICATION:
 * An alert that was generated by the system (e.g., "Contract X
 * expires in 30 days"). Can be read or unread, like an email inbox.
 */

// What an upcoming renewal looks like from the API
export interface UpcomingRenewal {
  contract_id: number;
  contract_title: string;
  contract_number: string | null;
  vendor_id: number;
  vendor_name: string;
  value: number | null;
  end_date: string;
  days_remaining: number;
  urgency: 'expired' | 'critical' | 'warning' | 'attention' | 'normal';
  status: string;
}

// What a notification looks like from the API
export interface Notification {
  id: number;
  contract_id: number;
  contract_title: string | null;
  vendor_name: string | null;
  notification_type: string;
  days_until_expiry: number;
  message: string;
  is_read: boolean;
  email_sent: boolean;
  recipient_email: string | null;
  created_at: string;
}

// Response from the check-now endpoint
export interface CheckNowResponse {
  message: string;
  new_notifications: number;
  notifications: Array<{
    contract_id: number;
    contract_title: string;
    vendor_name: string;
    type: string;
    days_remaining: number;
    recipient_email: string | null;
  }>;
  email_results: {
    sent: number;
    failed: number;
    skipped: number;
  };
}
